DROP TABLE IF EXISTS apitbl;
DROP TABLE IF EXISTS usertbl;

CREATE TABLE apitbl (
  id SERIAL PRIMARY KEY,
  lat FLOAT(53),
  lng FLOAT(53),
  name VARCHAR(255),
  vicinity VARCHAR(255),
  deadOrAlive VARCHAR(255),
  statusReason VARCHAR(255),
  votesTotal INTEGER,
  avgTotal NUMERIC(2,1),
  avgClean NUMERIC(2,1),
  avgEasyToFind NUMERIC(2,1),
  noToiletPaper NUMERIC(3),
  noToiletSeatCovers NUMERIC(3),
  genderSpecific BOOLEAN,
  restingArea BOOLEAN,
  mothersRoom BOOLEAN,
  changingStation BOOLEAN,
  bidet BOOLEAN,
  feminineProducts BOOLEAN,
  homeDB VARCHAR(10)
);

CREATE TABLE usertbl (
  id SERIAL PRIMARY KEY,
  lat FLOAT(53),
  lng FLOAT(53),
  name VARCHAR(255),
  vicinity VARCHAR(255),
  deadOrAlive VARCHAR(255),
  statusReason VARCHAR(255),
  votesTotal INTEGER,
  avgTotal NUMERIC(2,1),
  avgClean NUMERIC(2,1),
  avgEasyToFind NUMERIC(2,1),
  noToiletPaper NUMERIC(3),
  noToiletSeatCovers NUMERIC(3),
  genderSpecific BOOLEAN,
  restingArea BOOLEAN,
  mothersRoom BOOLEAN,
  changingStation BOOLEAN,
  bidet BOOLEAN,
  feminineProducts BOOLEAN,
  homeDB VARCHAR(10)
);

INSERT INTO apitbl (lat, lng, name, vicinity, deadOrAlive, statusReason, votesTotal, avgTotal, avgClean, avgEasyToFind, noToiletPaper, noToiletSeatCovers, genderSpecific, restingArea, mothersRoom, changingStation, bidet, feminineProducts,homeDB) VALUES (
  47.6100898,
  -122.3424699,
  'First Starbucks',
  '1912 Pike Place',
  'alive',
  '',
  100,
  3.5,
  2.5,
  4.1,
  100,
  100,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  'api'
);

INSERT INTO usertbl (lat, lng, name, vicinity, deadOrAlive, statusReason, votesTotal, avgTotal, avgClean, avgEasyToFind, noToiletPaper, noToiletSeatCovers, genderSpecific, restingArea, mothersRoom, changingStation, bidet, feminineProducts,homeDB) VALUES (
  47.6102198,
  -122.3424699,
  'Second Starbucks',
  '1912 Pike Place',
  'alive',
  '',
  100,
  3.5,
  2.5,
  4.1,
  100,
  100,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  'user'
);

INSERT INTO usertbl (lat, lng, name, vicinity, deadOrAlive, statusReason, votesTotal, avgTotal, avgClean, avgEasyToFind, noToiletPaper, noToiletSeatCovers, genderSpecific, restingArea, mothersRoom, changingStation, bidet, feminineProducts,homeDB) VALUES (
  47.6100998,
  -122.3424699,
  'Third Starbucks',
  '1912 Pike Place',
  'alive',
  '',
  100,
  3.5,
  2.5,
  4.1,
  100,
  100,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  'user'
);

INSERT INTO usertbl (lat, lng, name, vicinity, deadOrAlive, statusReason, votesTotal, avgTotal, avgClean, avgEasyToFind, noToiletPaper, noToiletSeatCovers, genderSpecific, restingArea, mothersRoom, changingStation, bidet, feminineProducts,homeDB) VALUES (
  47.6100898,
  -122.3425699,
  'Fourth Starbucks',
  '1912 Pike Place',
  'alive',
  '',
  100,
  3.5,
  2.5,
  4.1,
  100,
  100,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  'user'
);

INSERT INTO usertbl (lat, lng, name, vicinity, deadOrAlive, statusReason, votesTotal, avgTotal, avgClean, avgEasyToFind, noToiletPaper, noToiletSeatCovers, genderSpecific, restingArea, mothersRoom, changingStation, bidet, feminineProducts,homeDB) VALUES (
  47.6101098,
  -122.3428199,
  'Fifth Starbucks',
  '1912 Pike Place',
  'alive',
  '',
  100,
  3.5,
  2.5,
  4.1,
  100,
  100,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  'user'
);